---
baseURL: https://a-blank-slate.github.io
title: A Blank Slate
author: Ashish Mishra
copyright: Copyright © 2008–2021, A Blank Slate; all rights reserved.
publishDir: docs
paginate: "5"
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: hugo-PaperMod
canonifyURLs: true
params:
  description: This blog contains all the details which i have learnt in my Software carrer.
  author: Ashish Mishra
  ShowReadingTime: true
  contentTypeName: posts
  defaultTheme: auto
  ShowShareButtons: true
  profileMode:
    enabled: false
    title: Ashish Mishra
    imageUrl: "#"
    imageTitle: my image
    buttons:
    - name: Archives
      url: archives
    - name: Tags
      url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to A Blank Slate or I say my corner of the Internet.
    ContentSecondLine: My Blog is mostly a place to document things i learned.
  socialIcons:
  - name: stackoverflow
    url: https://stackoverflow.com/users/7188713/ashish-mishra
  - name: codepen
    url: https://codepen.io/ashishtwitting
  - name: github
    url: https://github.com/a-blank-slate
  custom_css : ["css/custom-style.css"]
markup:
  tableOfContents:
    endLevel: "3"
    ordered: false
    startLevel: "1"
menu:
  main:
  - url: "/series/"
    name: Series
    weight: "2"
  - url: "/tags/"
    name: Tags
    weight: "1"
  - url: "/archives/"
    name: Archives
    weight: "3"
taxonomies:
  category: categories
  tag: tags
  series: series
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
