---
baseURL: https://a-blank-slate.github.io
title: A Blank Slate
paginate: "5"
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
copyright: Copyright © 2008–2021, A Blank Slate; all rights reserved.
publishDir: docs
DefaultContentLanguage: en
canonifyURLs: true
minify:
  disableXML: true
languages:
  en:
    languageName: English
    weight: "1"
    menu:
      main:
      - name: Tags
        url: tags/
        weight: "1"
      - name: Search 🔍
        url: search/
        weight: "2"
      - name: Projects
        url: projects/
        weight: "3"
      - name: Archive
        url: archives
        weight: "4"

outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  env: production
  description: This blog contains the details which I have learnt in my Software carrier.
  author: Ashish Mishra
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  images:
  - android-chrome-512x512.png
  profileMode:
    enabled: false
    title: Ashish Mishra
    imageUrl: "#"
    imageTitle: my image
    buttons:
    - name: Archives
      url: archives
    - name: Tags
      url: tags
  homeInfoParams:
    Title: "A Blank Slate Blog \U0001F44B"
    Content: "- **This Blog contains posts on AEM, HUGO, REDIS, COUCH BASE and JAVA**"
  socialIcons:
  - name: github
    url: https://github.com/a-blank-slate
  - name: stackoverflow
    url: https://stackoverflow.com/users/7188713/ashish-mishra
  - name: codepen
    url: https://codepen.io/ashishtwitting
  - name: RsS
    url: index.xml
  custom_css:
  - css/custom-style.css
taxonomies:
  category: categories
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
