---
baseURL: https://the-tech-blog.github.io
title: The Tech Blog
author: Boring Baba
copyright: Copyright © 2008–2020, The Tech Blog; all rights reserved.
publishDir: docs
paginate: "10"
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: hugo-PaperMod
canonifyURLs: true
params:
  description: Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod
  author: Theme PaperMod
  ShowReadingTime: true
  contentTypeName: posts
  defaultTheme: auto
  ShowShareButtons: true
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
    - name: Archives
      url: archives
    - name: Tags
      url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to The Tech Blog or i say my corner of the internet. My Blog
      is mostly a place to document things i learned.
  socialIcons:
  - name: stackoverflow
    url: https://stackoverflow.com/users/7188713/ashish-mishra
  - name: codepen
    url: https://codepen.io/the-tech-blog
  - name: github
    url: https://github.com/the-tech-blog
markup:
  tableOfContents:
    endLevel: "3"
    ordered: false
    startLevel: "1"
menu:
  main:
  - url: "/series/"
    name: Series
    weight: "2"
  - url: "/tags/"
    name: Tags
    weight: "1"
  - url: "/archives/"
    name: Archives
    weight: "3"
taxonomies:
  category: categories
  tag: tags
  series: series
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
